# Generated by Django 2.1.2 on 2018-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocking', '0002_devicetype_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='devicetype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='network',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
