# Generated by Django 2.1.2 on 2018-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocking', '0004_auto_20181020_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='unlocking_time',
            field=models.CharField(default='3-5 Days', max_length=255),
            preserve_default=False,
        ),
    ]
