# Generated by Django 2.0.7 on 2018-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20180814_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSliderSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('background_image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Main slider',
            },
        ),
    ]
