# Generated by Django 2.0.7 on 2018-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_mainsliderslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsliderslide',
            name='colour',
            field=models.IntegerField(choices=[('Yellow', 1), ('Blue', 2), ('Orange', 3), ('Green', 4)], default=1),
        ),
    ]
