# Generated by Django 2.0.7 on 2018-08-15 10:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_mainsliderslide_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landline', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('opening_hours', models.TextField()),
                ('google_maps_place_id', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mainsliderslide',
            name='colour',
            field=models.IntegerField(choices=[(1, 'Yellow'), (2, 'Blue'), (3, 'Orange'), (4, 'Green')], default=1),
        ),
    ]
