# Generated by Django 2.0.7 on 2018-08-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_auto_20180827_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='google_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
