# Generated by Django 2.0.7 on 2018-09-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_auto_20180827_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairtype',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repairtype',
            name='repair_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
