# Generated by Django 2.0.7 on 2018-09-22 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_remove_repairtype_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTimeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
    ]
