# Generated by Django 2.0.7 on 2018-09-22 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_auto_20180922_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttimerule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
