# Generated by Django 2.0.7 on 2018-09-22 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_auto_20180922_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('uid', models.CharField(default=main_site.models.make_uid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointments', to='main_site.Customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_site.DeviceType')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_site.RepairType')),
            ],
        ),
    ]
