# Generated by Django 2.0.7 on 2018-09-29 11:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTimeBlockRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
