# Generated by Django 2.0.7 on 2018-09-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_appointmenttimeblockrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsliderslide',
            name='colour',
            field=models.IntegerField(choices=[(1, 'Yellow'), (2, 'Blue'), (3, 'Orange'), (4, 'Green'), (5, 'Black'), (6, 'Orange Inverse')], default=1),
        ),
    ]
