# Generated by Django 2.0.7 on 2018-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0019_auto_20180929_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='colour',
            field=models.IntegerField(choices=[(1, 'Yellow'), (2, 'Blue'), (3, 'Orange'), (4, 'Green'), (5, 'Black'), (6, 'Orange Inverse')], default=1),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
