# Generated by Django 2.0.7 on 2018-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0020_auto_20180929_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='featured_review',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='featured_review_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='name',
            field=models.TextField(),
        ),
    ]
