# Generated by Django 2.0.7 on 2018-09-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0021_auto_20180929_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='why_choose_us',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
