# Generated by Django 2.0.7 on 2018-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0022_siteconfig_why_choose_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('colour', models.IntegerField(choices=[(1, 'Yellow'), (2, 'Blue'), (3, 'Orange'), (4, 'Green'), (5, 'Black'), (6, 'Orange Inverse')], default=1)),
                ('button_text', models.CharField(max_length=255)),
                ('link_to', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='sellingpoint',
            name='title',
            field=models.TextField(),
        ),
    ]
