# Generated by Django 2.1.2 on 2018-10-15 12:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0023_auto_20180929_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='otherservice',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='repairtype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='sellingpoint',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicetype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsliderslide',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherservice',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairtype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellingpoint',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointments', to='main_site.Customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_site.DeviceType'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='repair',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_site.RepairType'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='main_site.Customer'),
        ),
        migrations.AlterField(
            model_name='postalorder',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='postal_orders', to='main_site.Customer'),
        ),
        migrations.AlterField(
            model_name='postalorder',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_site.DeviceType'),
        ),
        migrations.AlterField(
            model_name='postalorder',
            name='repair',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_site.RepairType'),
        ),
    ]
