# Generated by Django 2.1.2 on 2018-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0024_auto_20181015_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategory',
            options={'ordering': ('order',), 'verbose_name_plural': 'Device categories'},
        ),
        migrations.AlterModelOptions(
            name='mainsliderslide',
            options={'ordering': ('order',), 'verbose_name_plural': 'Main slider'},
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mainsliderslide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repairtype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellingpoint',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
