# Generated by Django 2.1.2 on 2018-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0025_auto_20181015_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsliderslide',
            name='link_to',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
