# Generated by Django 2.1.2 on 2018-10-20 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0026_mainsliderslide_link_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mainsliderslide',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='repairtype',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='sellingpoint',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='sellingpoint',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='appointment_description',
            field=ckeditor.fields.RichTextField(verbose_name='"Book an appointment" description'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='featured_review',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='opening_hours',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='post_description',
            field=ckeditor.fields.RichTextField(verbose_name='"Post" description'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='walk_in_description',
            field=ckeditor.fields.RichTextField(verbose_name='"Walk in" description'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='why_choose_us',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
