# Generated by Django 2.1.2 on 2018-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0028_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='anchor',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
