# Generated by Django 2.1.2 on 2018-10-25 10:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0030_auto_20181020_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='unlocking_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
