# Generated by Django 2.1.2 on 2018-10-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0031_siteconfig_unlocking_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='terms_and_conditions',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='warranty',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
