# Generated by Django 2.1.2 on 2018-11-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0032_auto_20181027_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_link_external',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherservice',
            name='is_link_external',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
