# Generated by Django 2.1.2 on 2018-11-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0033_auto_20181104_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairtype',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
