# Generated by Django 2.1.2 on 2018-11-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0035_auto_20181117_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsliderslide',
            name='anchor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='colour',
            field=models.IntegerField(choices=[(3, 'Red'), (1, 'Orange'), (2, 'Blue'), (4, 'Green'), (5, 'Black'), (6, 'Red Inverse')], default=1),
        ),
        migrations.AlterField(
            model_name='mainsliderslide',
            name='colour',
            field=models.IntegerField(choices=[(3, 'Red'), (1, 'Orange'), (2, 'Blue'), (4, 'Green'), (5, 'Black'), (6, 'Red Inverse')], default=1),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='colour',
            field=models.IntegerField(choices=[(3, 'Red'), (1, 'Orange'), (2, 'Blue'), (4, 'Green'), (5, 'Black'), (6, 'Red Inverse')], default=1),
        ),
    ]
