# Generated by Django 2.1.2 on 2018-11-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0036_auto_20181119_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='public_liability',
            field=models.FileField(blank=True, upload_to='', verbose_name='Public liability insurance certificate'),
        ),
    ]
