# Generated by Django 2.1.2 on 2018-11-22 14:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0037_siteconfig_public_liability'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_top_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='main_site.Customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.DeviceType'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.RepairType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main_site.Customer'),
        ),
        migrations.AlterField(
            model_name='postalorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postal_orders', to='main_site.Customer'),
        ),
        migrations.AlterField(
            model_name='postalorder',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.DeviceType'),
        ),
        migrations.AlterField(
            model_name='postalorder',
            name='repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.RepairType'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='unlocking_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='why_choose_us',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
