# Generated by Django 2.1.3 on 2019-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0038_auto_20181122_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecategory',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='devicecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='devicecategory',
            name='icon',
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
