# Generated by Django 2.1.3 on 2019-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0039_auto_20190601_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
