# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST https://api.worldpay.com/v1/tokens
Content-Type: application/json

{
  "reusable": true,
  "paymentMethod": {
        "name": "name",
        "expiryMonth": 2,
        "expiryYear": 2020,
        "cardNumber": "4444 3333 2222 1111",
        "type": "Card",
        "cvc": "123"
    },
  "clientKey": "T_C_52bc5b16-562d-4198-95d4-00b91f30fe2c"
}

###