kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: react
  namespace: website-test
  labels:
    app: website
    teir: react
  annotations:
    ingress.kubernetes.io/referrer-policy: "strict-origin-when-cross-origin"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
spec:
  rules:
  - host: test.wewillfixyourpc.co.uk
    http:
      paths:
      - path: "/"
        backend:
          serviceName: react
          servicePort: 80
  tls:
  - secretName: react-tls
    hosts:
    - test.wewillfixyourpc.co.uk
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: react-cert
  namespace: website-test
spec:
  secretName: react-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: test.wewillfixyourpc.co.uk
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - test.wewillfixyourpc.co.uk
---
kind: Service
apiVersion: v1
metadata:
  name: react
  namespace: website-test
  labels:
    app: website
    teir: react
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: website
    tier: react
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  namespace: website-test
spec:
  selector:
    matchLabels:
      app: website
      tier: react
  replicas: 3
  template:
    metadata:
      labels:
        app: website
        tier: react
    spec:
      containers:
      - name: react
        image: evilben/wwfypc-react:(hash)
        ports:
        - containerPort: 5000
        imagePullPolicy: Always



