# Generated by Django 2.0.7 on 2018-10-01 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_devicemodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategory',
            options={'verbose_name_plural': 'Device categories'},
        ),
        migrations.AddField(
            model_name='devicepermutation',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='permutations', to='selling.DeviceModel'),
            preserve_default=False,
        ),
    ]
