# Generated by Django 2.1.2 on 2018-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0006_auto_20181015_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategory',
            options={'ordering': ('order',), 'verbose_name_plural': 'Device categories'},
        ),
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='devicepermutation',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='devicepermutationvalue',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicepermutation',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicepermutationvalue',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
