kind: Service
apiVersion: v1
metadata:
  name: django
  namespace: website-test
  labels:
    app: website
    tier: django
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: website
    tier: django
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: website-test
spec:
  selector:
    matchLabels:
      app: website
      tier: django
  replicas: 3
  template:
    metadata:
      labels:
        app: website
        tier: django
    spec:
      volumes:
      - name: gluster
        glusterfs:
          endpoints: glusterfs-cluster
          path: apps
      containers:
      - name: django
        image: evilben/wwfypc-django:(hash)
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_HOST
          value: mysql.kube-system
        - name: DB_USER
          value: website-test
        - name: DB_NAME
          value: website-test
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: pass
        - name: WORLDPAY_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: worldpay
              key: server
        - name: DJANGO_SECRET
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: secret
        volumeMounts:
        - name: gluster
          mountPath: /src/static
          subPath: website-test/static
        - name: gluster
          mountPath: /src/media
          subPath: website-test/media



