apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: website-test
subsets:
  - addresses:
    - ip: 159.69.213.4
    ports:
    - port: 1
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: website-test
spec:
  ports:
  - port: 1
