kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: api
  namespace: website-test
  labels:
    app: website
  annotations:
    ingress.kubernetes.io/referrer-policy: "strict-origin-when-cross-origin"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
spec:
  rules:
  - host: api.test.wewillfixyourpc.co.uk
    http:
      paths:
      - path: "/"
        backend:
          serviceName: nginx
          servicePort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: website-test
  labels:
    app: website
    tier: nginx
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: website
    tier: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: website-test
spec:
  selector:
    matchLabels:
      app: website
      tier: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: website
        tier: nginx
    spec:
      volumes:
      - name: gluster
        glusterfs:
          endpoints: glusterfs-cluster
          path: apps
      containers:
      - name: nginx
        image: evilben/wwfypc-nginx:(hash)
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        volumeMounts:
        - name: gluster
          mountPath: /src/static
          subPath: website-test/static
        - name: gluster
          mountPath: /src/media
          subPath: website-test/media



