kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: website
  namespace: website
  labels:
    app: website
  annotations:
    ingress.kubernetes.io/referrer-policy: "strict-origin-when-cross-origin"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
spec:
  rules:
  - host: wewillfixyourpc.co.uk
    http: &website_http
      paths:
      - path: "/"
        backend:
          serviceName: old-site
          servicePort: 80
  - host: www.wewillfixyourpc.co.uk
    http: *website_http
  - host: mobile.wewillfixyourpc.co.uk
    http: *website_http
  - host: wewillfixyouripad.co.uk
    http: *website_http
  - host: www.wewillfixyouripad.co.uk
    http: *website_http
  - host: mobile.wewillfixyouripad.co.uk
    http: *website_http
  tls:
  - secretName: main-tls
    hosts:
    - wewillfixyourpc.co.uk
    - www.wewillfixyourpc.co.uk
    - mobile.wewillfixyourpc.co.uk
    - wewillfixyouripad.co.uk
    - www.wewillfixyouripad.co.uk
    - mobile.wewillfixyouripad.co.uk
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: main-cert
  namespace: website
spec:
  secretName: main-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wewillfixyourpc.co.uk
  dnsNames:
  - www.wewillfixyourpc.co.uk
  - mobile.wewillfixyourpc.co.uk
  - wewillfixyouripad.co.uk
  - www.wewillfixyouripad.co.uk
  - mobile.wewillfixyouripad.co.uk
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - wewillfixyourpc.co.uk
      - www.wewillfixyourpc.co.uk
      - mobile.wewillfixyourpc.co.uk
      - wewillfixyouripad.co.uk
      - www.wewillfixyouripad.co.uk
      - mobile.wewillfixyouripad.co.uk
---
kind: Service
apiVersion: v1
metadata:
  name: old-site
  namespace: website
  labels:
    app: old-site
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: old-site
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-site
  namespace: website
spec:
  selector:
    matchLabels:
      app: old-site
  replicas: 3
  template:
    metadata:
      labels:
        app: old-site
    spec:
      volumes:
      - name: gluster
        glusterfs:
          endpoints: glusterfs-cluster
          path: apps
      containers:
      - name: old-site
        image: evilben/wwfypc-old-site:(hash)
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
          - name: gluster
            mountPath: /var/www/html/upload
            subPath: website-old/html/upload
          - name: gluster
            mountPath: /var/www/html/wewillfixyouripad/upload
            subPath: website-old/html/wewillfixyouripad/upload
        env:
        - name: DB_HOST
          value: mysql.kube-system
        - name: DB_USER
          value: website-old
        - name: DB_NAME
          value: website-old
        - name: DB_NAME_IPAD
          value: website-old-ipad
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass-old
              key: pass
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: email-pass
              key: pass



