kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: website
  namespace: website
  labels:
    app: website
  annotations:
    ingress.kubernetes.io/referrer-policy: "strict-origin-when-cross-origin"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
spec:
  rules:
  - host: wewillfixyourpc.co.uk
    http: &website_http
      paths:
      - path: "/"
        backend:
          serviceName: old-site
          servicePort: 80
  - host: www.wewillfixyourpc.co.uk
    http: *website_http
  - host: wewillfixyouripad.co.uk
    http: *website_http
  - host: www.wewillfixyouripad.co.uk
    http: *website_http
#  tls:
#  - secretName: main-tls
#    hosts:
#    - api.test.wewillfixyourpc.co.uk
#---
#apiVersion: certmanager.k8s.io/v1alpha1
#kind: Certificate
#metadata:
#  name: main-cert
#  namespace: website
#spec:
#  secretName: main-tls
#  issuerRef:
#    name: letsencrypt-prod
#    kind: ClusterIssuer
#  commonName: wewillfixyourpc.co.uk
#  acme:
#    config:
#    - http01:
#        ingressClass: nginx
#      domains:
#      - wewillfixyourpc.co.uk
---
kind: Service
apiVersion: v1
metadata:
  name: old-site
  namespace: website
  labels:
    app: old-site
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: old-site
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-site
  namespace: website
spec:
  selector:
    matchLabels:
      app: old-site
  replicas: 3
  template:
    metadata:
      labels:
        app: old-site
    spec:
      containers:
      - name: old-site
        image: evilben/wwfypc-old-site:(hash)
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: mysql.kube-system
        - name: DB_USER
          value: website-old
        - name: DB_NAME
          value: website-old
        - name: DB_NAME_IPAD
          value: website-old-ipad
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass-old
              key: pass



