# Generated by Django 2.0.7 on 2018-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepcmodel',
            options={'verbose_name': 'Base PC model'},
        ),
        migrations.AddField(
            model_name='basepcmodel',
            name='image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
