# Generated by Django 2.0.7 on 2018-10-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc', '0002_auto_20181010_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('help_text', models.TextField()),
                ('base_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customisations', to='build_pc.BasePcModel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomisationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='build_pc.Customisation')),
            ],
        ),
        migrations.CreateModel(
            name='PcPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='build_pc.BasePcModel')),
                ('options', models.ManyToManyField(to='build_pc.CustomisationOption')),
            ],
        ),
    ]
