# Generated by Django 2.0.7 on 2018-10-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc', '0004_auto_20181012_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcPostage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postage', to='build_pc.PcPrice')),
            ],
        ),
    ]
