# Generated by Django 2.1.2 on 2018-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc', '0005_pcpostage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcprice',
            name='options',
            field=models.ManyToManyField(blank=True, to='build_pc.CustomisationOption'),
        ),
    ]
