# Generated by Django 2.1.2 on 2018-10-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc', '0007_auto_20181015_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcprice',
            name='base_pc',
        ),
        migrations.RemoveField(
            model_name='pcprice',
            name='options',
        ),
        migrations.AddField(
            model_name='basepcmodel',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customisationoption',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pcpostage',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postage', to='build_pc.BasePcModel'),
        ),
        migrations.DeleteModel(
            name='PcPrice',
        ),
    ]
