# Generated by Django 2.1.2 on 2018-10-20 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc', '0008_auto_20181015_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepcmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='customisation',
            name='help_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
