# Generated by Django 2.0.7 on 2018-08-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'Item categories'},
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=99),
            preserve_default=False,
        ),
    ]
