# Generated by Django 2.1.2 on 2018-10-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_and_sell', '0005_item_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='buy_and_sell.ItemCategory'),
        ),
    ]
