# Generated by Django 2.1.2 on 2018-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180922_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='servicepagesection',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='servicepage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicepagesection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
