# Generated by Django 2.1.2 on 2018-10-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20181015_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='header_background',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
