# Generated by Django 2.1.2 on 2018-10-20 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicepage_header_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepagesection',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicepagesection',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
