# Generated by Django 2.1.2 on 2018-11-14 14:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20181020_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='header_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
