# Generated by Django 2.1.2 on 2018-11-17 13:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicepage_header_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='header_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
